services:
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - "${CLIENT_HOST}:${CLIENT_PORT}"
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./client:/app/
      - /app/node_modules
    container_name: client
  server:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - "${SERVER_HOST}:${SERVER_PORT}"
    network_mode: "host"
    volumes:
      - ./server:/app/
      - /app/node_modules
    container_name: server
  # entrypoint: npm start
volumes:
  data:
